x=msgbox("Du" ,0, "Carl Mar")
x=msgbox("Ser" ,0, "Carl Mar")
x=msgbox("Da" ,0, "Carl Mar")
x=msgbox("Egentlig" ,0, "Carl Mar")
x=msgbox("Rimelig" ,0, "Carl Mar")
x=msgbox("Fræk" ,0, "Carl Mar")
x=msgbox("Ud" ,0, "Carl Mar")
x=msgbox("<3" ,0, "Carl Mar")
